main: com.PersonBelowRocks.myplugin.MyPlugin
name: MyPlugin
version: 1.0
api-version: 1.16
description: Yo wassup this is my plugin
commands:
  getwand:
    description: Get the Stick of Zeus
    usage: /<command>

  track:
    description: Get a player tracker
    usage: /<command> [player]

  untrack:
    description: Stop tracking
    usage: /<command>

  trackreload:
    description: Reload tracking configuration
    usage: /<command>
# PERMISSIONS
permissions:
  playertracker.track:
    description: Track other other.
    default: true
  playertracker.untrack:
    description: Stop tracking.
    default: true
  playertracker.reload:
    description: Reload configuration.
    default: op
